# Generated by Django 3.1.7 on 2021-03-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('played_at', models.DateTimeField()),
                ('href', models.CharField(max_length=500)),
            ],
        ),
    ]
